### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by Rahmiel** [abluescarab/tModLoader-WingSlot#1]
Having some issues with wings acting really weird (including being invisible) when in your slot on a multiplayer server. The issue isn't game breaking just ugly. Also want to note the wings currently do not have a dye slot, would be a nice feature for the future.

Edit: When left clicking wings in the slot on multiplayer it toggles the PvP button. Might need to move the Wing Slot somewhere else.

**Comment by abluescarab** [comment]
Rahmiel,

I was not aware of this issue. Thanks for bringing it to my attention! I'll have to see what I can do, but I'm kind of busy with classes at the moment, so I'll have to find some free time. I also have had a request for a dye slot on the forums, so that's next on my list.

**Comment by abluescarab** [comment]
Rahmiel,

I'm not sure about the invisible wing glitch because I can't seem to replicate it. I have compiled the mod for Terraria 1.3.3.2, however, and fixed the PVP icon glitch. I'll close this issue and feel free to post another one if any other bugs persist.
