### ISSUE TITLE
Wings wont equip

### ISSUE THREAD

**Issue by Acompleteturtle** [abluescarab/tModLoader-WingSlot#11]
Hey I've noticed that some wings wont work (probably because you cant cover every mod). when ever I left click and pick up my wings it automatically switches to equipables pg 1 and locks me out of pg 2, where your wing slot is. So if there isn't already, could you add an option where theres an option for it being on page 1 or page 2? hopefully you understand, thx.

**Comment by Acompleteturtle** [comment]
It might just be the mod tho, its called ZM in the recipe browser so...

**Comment by zauberparacelsus** [comment]
You need to right-click the wing to equip it to a secondary slot.  AFAIK, wings can't be put on pg2 directly due to limitations in tmodloader.

Also, shift-rightclick is used for the vanity wing slot, however it should be noted that the auto trash mod overrides this key combo.

**Comment by abluescarab** [comment]
@zauberparacelsus, thanks for your help in replying to this.

@Acompleteturtle, zauber is right, there are limitations in tModLoader that prevent me from changing the way equip pages work. You'll need to right-click the wings to equip in the normal slot and shift-right-click the wings to equip in the vanity slot.

It's true, I can't account for every mod. The mod currently checks whether or not an item is a set of wings by checking if `item.wingSlot > 0`. Some mods may handle this differently, though it should be compatible with *most*, if not all, mods.

Feel free to open a new issue if you have any more problems, but this one is solved by doing what I mentioned above.
