### ISSUE TITLE
Wings don't work properly with capes

### ISSUE THREAD

**Issue by MrRapenstien** [abluescarab/tModLoader-WingSlot#12]
normally, if you have wings and a cape you can turn off visibility on the wings and the cape will show over them as long as you're on the ground, right now the cape is completely invisible and the wings always show

Edit: this only happens when you have a different pair of wings in the vanity slot

**Comment by abluescarab** [comment]
I'm sorry, but this is actually Terraria's default behavior. Here's an example with the Wing Slot mod disabled:

![terraria](https://user-images.githubusercontent.com/5298903/33532298-4d9d6384-d84d-11e7-9e45-fcf552fd3e18.gif)
