### ISSUE TITLE
Also can't unequip wings

### ISSUE THREAD

**Issue by Bogeynator** [abluescarab/tModLoader-WingSlot#21]
I saw others with this issue, but I didn't find anything to fix it. As the title states, I can't unequip the wings I put on in the wing slot or the vanity slot. The previous version (which let you put non-wing accessories in the wing slot) worked fine. I've tried closing and re-opening the world and restarting the game, but neither has worked.

**Comment by merlinx2k** [comment]
got the same problem.

**Comment by abluescarab** [comment]
Thanks for letting me know. I'm working on a hotfix right now.
