### ISSUE TITLE
Mod doesn't appear in tModloader

### ISSUE THREAD

**Issue by EponPL** [abluescarab/tModLoader-WingSlot#23]
Title says all.

**Comment by Nihgtmare6765** [comment]
For me, it shows up in the TModloader mod browser, but every time I try to download it, it looks like it went through, but it doesn't actually show up in my mod list.

**Comment by GalacticAcid** [comment]
I have the same issue too.

**Comment by DiabeticBacon** [comment]
Same here, doesnt download

**Comment by ComputationalPotato** [comment]
Same for me, and the tmod file is in the mods folder and the enabled.json file has wingslot in it. Also, my character says that wingslot is missing.

**Comment by mckittens20** [comment]
i also have this issue where it won't enable/ appear in the mod list

**Comment by RuynTheWorld** [comment]
Having the same issue. The mod itself is in the mod folder, but tmodloader doesn't detect it in any way possible, I've tried manually putting the mod in the folder in case its some tmodloader shenanigans but to no avail.

**Comment by NinjaRale** [comment]
Thought I was the only one. Tried a ton of stuff; went into the mod folder and tried messing around in there but to no success.

**Comment by Nextshot** [comment]
Lol I've just updated it and it is downloadable but cant be enabled and even on manual download from the forum it is still missing
(Also I forgot to take out the wing from the slot and lost my wing xd)

**Comment by Nextshot** [comment]
If I knew that this mod would be such a pain I would have just used the 'Celestial Onion' instead :/

**Comment by abluescarab** [comment]
Hello, everyone. I would recommend downloading [v1.4.1](https://github.com/abluescarab/tModLoader-WingSlot/releases/tag/v1.4.1) until further notice. This is an issue that I will do my best to figure out. I am working on it right now.

**Comment by Nextshot** [comment]
Btw what was the problem that was causing it to not appear, function and appear at all ?

**Comment by abluescarab** [comment]
The mod file corrupted while I was compiling it. It was a known issue with tModLoader.
