### ISSUE TITLE
WingSlot forces wings onto the slot with no way of controlling behaviour

### ISSUE THREAD

**Issue by Jofairden** [abluescarab/tModLoader-WingSlot#25]
I'll get straight to the point.

Problem: I have a UI that players can place their item in by right clicking it and holding left control.
The problem is that this causes the items to duplicate, as they are also force placed into WingSlot's slot for wings, and I haven't found a way to have WingSlot not do this behaviour. The class is also internal.

Im fine with anything, setting a bool to force it to go away for example, or having the class be public and clear the slot myself. Either way, it has become a mod conflict that is quite annoying as it allows duplication of items.

For now, I have disabled the functionality for wings in EMM itself so that it can not trigger the issue.

**Comment by abluescarab** [comment]
I added an option to the mod config a few versions ago to allow equipping the wings in an accessory slot. It's found in the tModLoader "Mod Configs" folder. Would this be what you're looking for?

**Comment by abluescarab** [comment]
I've made the class and some of its private methods public. Can you please try out the version on the [emm](../tree/emm) branch and let me know if that works for you?

**Comment by abluescarab** [comment]
> Of course I can use reflection and do finicky stuff, but I'd rather stay away from that. I hope you understand.

Of course I do! I'm just trying to work with you to figure out the best way to implement this functionality. I've updated the [emm](../tree/emm) branch to use the `Call()` function to implement a list of override functions like your second suggestion.

To override equipping:
```csharp
wingSlot.Call(/* "add" or "remove" */, /* func<bool> that returns true to equip/false to cancel */);
```

I'd feel more comfortable making `WingSlotPlayer` internal again, if this works and you feel it's okay with this implementation.

**Comment by Jofairden** [comment]
Yes, this should work. Feel free to make them internal again if you want. Thanks

**Comment by abluescarab** [comment]
v1.6.0 is pushed out with the changes.

**Comment by Jofairden** [comment]
Hey, it doesn't seem to work:
```cs
WingSlotLoaded = wingSlotMod != null && wingSlotMod.Version >= new Version(1, 6, 1);

				if (WingSlotLoaded)
				{
					wingSlotMod.Call("add", (Func<bool>)(
						() => 
							!CubeInterface.IsVisible));
				}
``` 
WingSlotLoaded is true, the Call correctly returns null. However, my function is never being called.

**Comment by Jofairden** [comment]
So I tried debugging your mod, and Slot_Conditions is never called (I put a breakpoint on it)
So it makes sense that my function is never called either

**Comment by Jofairden** [comment]
Ah, now I see. It only triggers when I manually press the slot, not on right click. Right click is the functionality I needed.

**Comment by Jofairden** [comment]
So, there will need to be changes. The actual problem is that I added a _right click_ functionality to my UI, which if used would put it in my UI and also yours. What I need this to be able to do is not have it put it in your UI on right click. Manually putting it in the slot is of no concern.

**Comment by Jofairden** [comment]
Thanks, I'll be able to test it later.

**Comment by Jofairden** [comment]
I cannot compile your mod, 
`d:\Admin\Documents\My Games\Terraria\ModLoader\Mod Sources\WingSlot\GlobalWingItem.cs(4,7) : error CS0246: The type or namespace name 'TerraUI' could not be found (are you missing a using directive or an assembly reference?)`
Can you provide me with a built .tmod ?

**Comment by Jofairden** [comment]
Alright, I tested it and it doesn't work. I tried reversing my logic as well, but both ways it still ends up in your slot as well.

**Comment by abluescarab** [comment]
Please let me know when you finish adding this functionality to your mod so I can safely close this issue.

**Comment by Jofairden** [comment]
You can safely close the issue.
