### ISSUE TITLE
Multiplayer v.2

### ISSUE THREAD

**Issue by Rahmiel** [abluescarab/tModLoader-WingSlot#3]
Okay last time I was here I posted some issues and didn't really go into detail, I've done testing since the most recent update. So lets do this!

In Multiplayer you cannot see OTHER player's wings, and their movement becomes quite erratic. It doesn't affect game-play at all, its just very ugly. Its not a high priority issue at all. I also want to note that this was only tested with Non-vanilla wings, specifically the wings from Thorium Mod. I will test with vanilla wings when I get the chance (or more accurately the people to test it).

P.S. Thanks for moving the slot over, no more PvP issues 👍

**Comment by Rahmiel** [comment]
I have tested it, Vanilla wings do it too. Its not a super big deal but it makes it difficult for our Healer to heal us (Thorium adds a healing class) because we are teleporting around for him.

**Comment by abluescarab** [comment]
I am aware this issue is still around, but the tModLoader documentation is terrible and I can't figure out how to fix this in multiplayer. I'll poke around other modders' source codes, but I can't guarantee this will get fixed any time soon.
