### ISSUE TITLE
Wings don't work well with balloons

### ISSUE THREAD

**Issue by ernieIzde8ski** [abluescarab/tModLoader-WingSlot#30]
Having wings equipped at the same as balloons results in the balloons being used at the same time as the wings, which doesn't work out too well. It seems to slow it down, even. I've only tested with the bundle of balloons.

**Comment by abluescarab** [comment]
I can't reproduce this issue on my end.

**Comment by ernieIzde8ski** [comment]
[I tried again](https://youtu.be/owEuLn3K89Y) & while the wing time being consumed at the same time as balloons was kinda annoying, I did not notice any unusual behavior to Terraria besides a different glitch.
