### ISSUE TITLE
Soul of Eternity crash

### ISSUE THREAD

**Issue by Arpeak** [abluescarab/tModLoader-WingSlot#33]
The game crashes when hovering over Fargo's Soul of Eternity in the inventory after unequipping it from the wing slot. Also the sprite is unusually large when it's equipped.
[https://streamable.com/h32ii](url)
log: [https://pastebin.com/TsPMk7wv](url)

**Comment by abluescarab** [comment]
This appears to be fixed in the latest version of Wing Slot.
