### ISSUE TITLE
Breakage in tModLoader 0.11.7.1

### ISSUE THREAD

**Issue by zauberparacelsus** [abluescarab/tModLoader-WingSlot#35]
Under tModLoader 0.11.7.1 and 0.11.7.2, the wing slots can no longer have items placed in them or removed, including the vanity slot and the dye slot.  Wings can still be equipped by right-clicking them and still function, but otherwise the slots do not work.

**Comment by SevenJace** [comment]
Any Follow up on this? Just Installed the mod and this happened. Now my wings are being held hostage on the slot XD

**Comment by abluescarab** [comment]
Hi, I apologize for the delay. I don't have a lot of time to work on the mod at the moment but I will try to get to it as soon as possible.

**Comment by zauberparacelsus** [comment]
I have discovered that the issue does not lie in tModLoader.  Rather, it is a conflict with the Base Library mod, which is one of the dependencies for the Portable Storage 2 mod.  Base Library is also causing other UI-related bugs, such as text being entered into the search fields for Magic Storage and being unable to scroll through chat history.

I am closing this bug report, since the problem is just another mod conflicting with stuff.
