### ISSUE TITLE
Main wing slot cannot be accessed

### ISSUE THREAD

**Issue by Zemogiter** [abluescarab/tModLoader-WingSlot#36]
Moving wings from inventory to slot and clicking on it does nothing. Shift-right click for vanity slot works but moving wing to vanity slot normally also dosen't work.
[client.log](https://github.com/abluescarab/tModLoader-WingSlot/files/4703863/client.log)

**Comment by zauberparacelsus** [comment]
Do you have the Base Library mod installed?  The current version is causing several UI problems, including a breakage with putting stuff into the wing slot.

(Base Library is a dependency for the Portable Storage mod, and a few other mods by Itorius.)

**Comment by Zemogiter** [comment]
Yes I have this mod for that very reason.

**Comment by IceMaverick** [comment]
I just wish to comment that (as of 11.7.5 of tModLoader) I am having the listed issue *without* Itorius's Base Library installed.

**Comment by Xiarno** [comment]
> I just wish to comment that (as of 11.7.5 of tModLoader) I am having the listed issue _without_ Itorius's Base Library installed.

As of the current version of tModLoader (v0.11.7.7), the Base Library mod still does this problem but uninstalling it fixes it.

**Comment by abluescarab** [comment]
I appreciate the input, everyone. If this is caused by the Base Library mod, then the issue will have to be brought up with that mod's developer.
