### ISSUE TITLE
Wings disappearing all the time.

### ISSUE THREAD

**Issue by ConaII** [abluescarab/tModLoader-WingSlot#39]
Updated to version 1.8.0.

I understand that the first time, it disappears, but it keeps disappearing even after putting new ones.
It's really annoying.

**Comment by abluescarab** [comment]
Hi, can you give me steps to reproduce this issue?

**Comment by EstelarGalaxus** [comment]
It happened to me and my friends too
we are playing with various mods and it was all well until the update
when my friends joined my world my wings, vanity wings and even dye vanished
it wasn't yus a visual glitch, they were gone, i haven't trien in single player but it seem like a multiplayer bug since it was fine til my friend joined

**Comment by abluescarab** [comment]
@EstelarGalaxus: Were you using a dedicated server or Host & Play? Did you remove the wings and dye from the slots before updating?

**Comment by abluescarab** [comment]
Additionally, your wings will not display correctly in multiplayer. This is a known issue. The wings will remain the slots and still work, but they are not visible to other players.

**Comment by EstelarGalaxus** [comment]
it was on host and play, i forgot to remove before update (cause i didnt know this mod was the one being updated (i just press update all in the mod browser)) and in wasnt a display error, i couldn't fly unles i equiped other pair of wings, my friend did that but his desapeared again

**Comment by ConaII** [comment]
Yeah, it was on multiplayer with thorium.
I cheated various wings and they disappeared all the time, sometimes it vanishes but it's still usable and then it completly disappears.

I just downgraded the version.

**Comment by abluescarab** [comment]
I have been able to reproduce this issue. I've given it high priority to fix.
