### ISSUE TITLE
Loot bag based mods bugged with the Wing Slot

### ISSUE THREAD

**Issue by mesemi** [abluescarab/tModLoader-WingSlot#41]
This was not occuring previous to the update.
Opening bags from the LootBags and the Bags mod seems to open the bag and give you the stuff properly, however the bag goes to the wing slot upon right clicking it giving you a theoretical infinite amount of bags if you wish to spend the time.
Probably something with rightclicking it in the new update causes it to go to the wing slot despite not being wings?

It does not allow me to place the bag there in the slot by itself- it has to be right clicked in.
![lootbag](https://user-images.githubusercontent.com/45022855/149424888-74cfa60f-85e2-4d28-92cb-6134c8036bd4.png)

**Comment by abluescarab** [comment]
Hi, this was fixed in v1.8.1, released about 15 minutes ago. Please update the mod.
