### ISSUE TITLE
Fails to compile on latest stable tmodloader due to extending a non-existent class.

### ISSUE THREAD

**Issue by retcinder** [abluescarab/tModLoader-WingSlot#54]
https://github.com/abluescarab/tModLoader-WingSlot/blob/e9b69bc619729e30f84bb7f5fe011f0ebdf1c922/WingSlotPlayer.cs#L9C1-L9C1
By changing the class being extended to just "ModPlayer", it will successfully compile and load again.

**Comment by abluescarab** [comment]
Thanks for bringing this issue to my attention. I've changed it the way you recommended and the mod has been updated.
